M48
; DRILL file {KiCad 8.0.4} date 2024-08-09T22:43:34-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-09T22:43:34-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1063
%
G90
G05
T1
X3.4724Y-5.4236
X3.7Y-5.4236
T2
X4.9069Y-2.0878
X5.0152Y-2.0878
T3
X2.8433Y-5.5634
X2.9614Y-5.5634
T4
X2.4449Y-5.5315
X4.7283Y-5.5315
M30
